/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.2/samples
 */
plugins {
    java
    id("io.freefair.lombok") version "6.4.3"
    id("org.springframework.boot") version "2.6.7"
    id("io.spring.dependency-management") version "1.0.11.RELEASE"
    id("com.diffplug.spotless") version "6.5.1"
}

group = "per.shantanu.poc.sailpoint"
version = "1.0.0-SNAPSHOT"

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(11))
        vendor.set(JvmVendorSpec.ADOPTOPENJDK)
    }
}

spotless {
    java {
        googleJavaFormat("1.8")
        removeUnusedImports()
        endWithNewline()
        trimTrailingWhitespace()
    }
}

repositories {
    mavenCentral()
}

val awsSDKVersion = "2.17.130"

dependencyManagement {
    imports {
        mavenBom("software.amazon.awssdk:bom:$awsSDKVersion")
    }
}

dependencies {
    annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")

    implementation("org.springframework.boot:spring-boot-starter-webflux")
    implementation("software.amazon.awssdk:dynamodb")
    implementation("software.amazon.awssdk:netty-nio-client")
    implementation("com.google.code.findbugs:annotations:3.0.1")
    implementation("com.google.code.findbugs:jsr305:3.0.1")

    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("io.projectreactor:reactor-test")
}

tasks.withType<org.springframework.boot.gradle.tasks.bundling.BootBuildImage> {
    imageName = "${project.name}:${project.version}"
    builder = "paketobuildpacks/builder:tiny"
}