version: "3.8"
services:
  dynamodb:
    build:
      context: ./infra
      dockerfile: Dockerfile
    container_name: dynamodb_local
    ports:
      - "8000:8000"
    volumes:
      - ./infra/init-db:/home/dynamodblocal/db
  app:
    image: atm-service:1.0.0-SNAPSHOT
    container_name: application
    ports:
      - "8080:8080"
volumes:
  init-db:
    driver: local